### ISSUE TITLE
添加了action过后呢？如何操作，怎么定义多久时间登录一次，登录日志有吗

### ISSUE THREAD

**Issue by 3377** [lopins/serv00-auto-scripts#2]

**Comment by lopins** [comment]
> _No description provided._

https://github.com/lopins/serv00-auto-scripts/blob/871a0ba8944d7b3c425fdd95a82ccaac1470c54f/.github/workflows/login.yml#L7

这行参数就是定义计划任务的，具体参数你可以网上找 `cron表达式`，我这个库里面默认是一周执行一次，启用路径

![image](https://github.com/user-attachments/assets/eadde864-3799-4aa3-8ad3-1da531d5ed99)
