### ISSUE TITLE
x10hosting

### ISSUE THREAD

**Issue by aprday** [lopins/serv00-auto-scripts#3]
大佬，x10hosting，这个站每30天都需要登陆https://x10hosting.com/login。能不能搞个自动保号的方式？

**Comment by lopins** [comment]
> 大佬，x10hosting，这个站每30天都需要登陆[https://x10hosting.com/login。能不能搞个自动保号的方式？](https://x10hosting.com/login%E3%80%82%E8%83%BD%E4%B8%8D%E8%83%BD%E6%90%9E%E4%B8%AA%E8%87%AA%E5%8A%A8%E4%BF%9D%E5%8F%B7%E7%9A%84%E6%96%B9%E5%BC%8F%EF%BC%9F)

有人机验证码，recaptcha，参考这篇思路：[使用python selenium解决谷歌验证码(reCAPTCHA)](https://www.cnblogs.com/mswei/p/15568461.html)

**Comment by boosoyz** [comment]
> 大佬，x10hosting，这个站每30天都需要登陆[https://x10hosting.com/login。能不能搞个自动保号的方式？](https://x10hosting.com/login%E3%80%82%E8%83%BD%E4%B8%8D%E8%83%BD%E6%90%9E%E4%B8%AA%E8%87%AA%E5%8A%A8%E4%BF%9D%E5%8F%B7%E7%9A%84%E6%96%B9%E5%BC%8F%EF%BC%9F)

x10hosting_login.py登录脚本

```import requests

# 创建一个 session 对象
session = requests.Session()

# 你的 User-Agent
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"

# 设置请求头
headers = {
    "User-Agent": user_agent,
    "Referer": "https://x10hosting.com/login",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "zh-CN,zh;q=0.9",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1"
}

# 你的 Cookies
cookies = {
    "XSRF-TOKEN": "你的 XSRF-TOKEN 值",
    "x10hosting_session": "你的 x10hosting_session 值"
}

# 访问面板页面
response = session.get("https://x10hosting.com/panel", headers=headers, cookies=cookies)

# 检查是否成功访问
if response.status_code == 200:
    print("登录成功")
else:
    print(f"登录失败，状态码: {response.status_code}")
```
