### ISSUE TITLE
能不能增加上CT8啊

### ISSUE THREAD

**Issue by bbylw** [lopins/serv00-auto-scripts#5]
现在不支持CT8

**Comment by lopins** [comment]
> 现在不支持CT8

CT8是什么？

**Comment by lopins** [comment]
> > 现在不支持CT8
> 
> CT8是什么？

https://github.com/lopins/serv00-auto-scripts/blob/a807b3af83bd7cee0542df5b8fc40d4024583d6d/login.js#L23C1-L23C67

改一下这行的就可以了

**Comment by lopins** [comment]
> > > 现在不支持CT8
> > 
> > 
> > CT8是什么？
> 
> https://github.com/lopins/serv00-auto-scripts/blob/a807b3af83bd7cee0542df5b8fc40d4024583d6d/login.js#L23
> 
> 改一下这行的就可以了
> 
> https://panel.ct8.pl/login/?next=/

已支持 CT8
